### PR TITLE
Release/1.6.0

### PR DESCRIPTION
**Pull request by bvarner**
Minor version bump for significant new features.

Release will close issues #56, #55, and #44.

### CODE REVIEW

**Comment by bvarner** [comment]
@raehalme Would you be so kind as to run a build off this branch and help kick the tires before I merge this to master and publish the artifacts in central?

**Comment by raehalme** [comment]
@bvarner Sorry for not being able to respond sooner, I totally get your impatience :-) I'll test the release asap and report any findings.

**Comment by bvarner** [comment]
No worries. I still haven't pushed to central, so there's still time!

**Comment by raehalme** [comment]
Detecting the branch works as intended, thanks!

**Comment by bvarner** [comment]
Excellent! Tagging works too, now with the scm manager. Thanks @raehalme for the inspiration.

**Pull request merged**
