### PR TITLE
New goal set-git-properties

### PR DESCRIPTION
**Pull request by rhierlmeier**
This PR introduces the goal set-git-properties that provides information about the branch name and type to the Maven build.
In implements the feature request https://github.com/egineering-llc/gitflow-helper-maven-plugin/issues/131.

### CODE REVIEW

**Comment by bvarner** [comment]
Thanks for the PR!

**Comment by glimmerveen** [comment]
Hi @rhierlmeier & @bvarner  , I noticed when building this project using JDK11 I got the following warning while running the JUnit tests:

> Warning: Nashorn engine is planned to be removed from a future JDK release

When looking at https://openjdk.org/jeps/372 , it is clear that modern JDK versions no longer have this scripting capability.

In order for this new feature to be used with modern JDKs, I think an alternative for the ScriptEngine should be sought.

**Comment by rhierlmeier** [comment]
It replaced with #139 Javascript with Groovy.

**Comment by glimmerveen** [comment]
> It replaced with #139 Javascript with Groovy.

Nice to see you only needed to swap the scripting language in the test! :)

**Pull request merged**
